name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 12
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
    - name: Build
      run: npm run build
    - name: Setup SSH
      uses: actions/setup-ssh@v1
      with:
        ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Deploy
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@users.noreply.github.com"
        git remote set-url origin git@github.com:miikaok/electron-kide-app-bot.git
        git add -A
        git commit -m "Deploy to GitHub Pages"
        git push origin HEAD:gh-pages
