name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and deploy
      run: |
        npm install --legacy-peer-deps
        npm run build
        npx gh-pages -d build
