name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        repository: git@github.com:miikaok/electron-kide-app-bot.git
    - name: Build and deploy
      run: |
        npm install --legacy-peer-deps
        npm run build
        npx gh-pages -d build
