name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 12
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: upload build files
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build
    - name: Deploy
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@users.noreply.github.com"
        git remote set-url origin git@github.com:miikaok/electron-kide-app-bot.git
        git fetch
        git branch -D gh-pages
        git checkout -b gh-pages
        git reset --hard origin/gh-pages
        git add -A
        git commit -m "Deploy to GitHub Pages"
        git push origin gh-pages
